### ISSUE TITLE
Sometimes await generateImage never returns and tests timeout

### ISSUE THREAD

**Issue by olignyf** [dferber90/jsdom-screenshot#22]
With some certain page content, the server under the hood to take a screenshot from never serves the webpage and the generateImage never returns.
I try to access the server's url like `http://localhost:60957/` and it hangs too until I hit Ctrl-C on my unit tests command, then suddenly the pages loads once correctly.
I will try to gather more information and submit some fixes if possible. I'm interested in some pointer if people have clues what could be causing this.

**Comment by dferber90** [comment]
It's been a very long time since I worked on this, so all I can offer is a wild guess. Something that comes to mind is that I think I used the `waitUntil` option and it could be that your website just stays busy making some long-running requests?

https://github.com/dferber90/jsdom-screenshot/blob/master/generateImage.js#L75

**Comment by dferber90** [comment]
I'm open to reopening this issue if you can come up with a reproduction :)

I'll close it for now as it's not really actionable on my side. Hope that's okay!

**Comment by olignyf** [comment]
I already found a fix for it. I can reproduce it easily with my work project which I cannot share, but will try to do a smaller one on github to reproduce.
