### ISSUE TITLE
Can we take component level screenshot with CSS

### ISSUE THREAD

**Issue by abhagupta** [dferber90/jsdom-screenshot#8]
First of all, great tool. Thanks for creating it.   I tried using it but could only get screenshot without any styling. Is there a way a component can be rendered and screenshot with CSS?  All examples that I found was rendering the <App /> first and then screenshot will capture a selector. However in a complicated app which has multiple components, tests are written inside the components to render only that component. Unfortunately, when you take a screenshot, the screenshots do not inherit the CSS which the parent component may be importing.  Any ideas around here?

**Comment by dferber90** [comment]
This is an old project which i'm not working on any more, so the answer is based on what I remember from back then. You would need to make sure that the styles are available inside `jsdom`. If you are testing your component using something like `jest`, then you would need to ensure that the CSS does not get turned into empty styles through jest.

This section from the README points you towards more information:

> This package can be paired with [jest-transform-css](https://github.com/dferber90/jest-transform-css) and [jest-image-snapshot](https://github.com/americanexpress/jest-image-snapshot) to enable Visual Regression Testing in Jest. See [jest-transform-css](https://github.com/dferber90/jest-transform-css) for more information.

Note that all of this was highly experimental back then, and I abandoned it since. I would recommend using a service like https://percy.io/ for your tests.

**Comment by abhagupta** [comment]
thanks for your answer. It truly helped me understand the whole thing.  I think I have reached a point, where I am using your jest transformer `jest-transform-css` but our app is using stylus, which means CSS modules.  According to your instructions I enabled the CSS modules, but now my .styl files are not compiling in Jest.  I am assuming that I have to change the post-runner.js.   I have very less experience in this, but I am assuming that I have to use a post-css for stylus files.  Please correct me if I am wrong.
